## EDUNET FOUNDATION - Self-Practice Exercise Notebook

### LAB 8 - Implementing Numpy Concepts in Python

Problem 1: Write a NumPy program to test whether none of the elements of a given array are zero.

In [3]:
import numpy as np
arr = np.array([0, 2, 3, 4, 5])
print(np.all(arr!=0))

False


Problem 2: Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [9]:
a=np.zeros(10)
b=np.ones(10)
c=np.full(10,5)
print(a,b,c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [5 5 5 5 5 5 5 5 5 5]


Problem 3: Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [14]:
a=np.random.randn(15)
print(a)

[ 1.46429647e-01 -2.17123795e-01 -6.11917969e-01 -1.10334730e-03
 -1.00192379e+00 -4.58524953e-01 -4.58886021e-01 -8.08145140e-01
  8.74363491e-01  4.52465626e-01 -1.73572480e+00 -1.33095925e-01
  3.39520656e-01  8.32110223e-01 -1.26066446e+00]


Problem 4: Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).

In [26]:
a=np.random.normal(200,7,(8,5))
print(a)

[[205.67426773 197.45385322 210.68542735 204.9624836  191.65560099]
 [193.15138882 201.96669845 206.08176284 205.90527431 206.4763274 ]
 [206.84538298 193.87206547 218.0669397  194.74406861 190.0662275 ]
 [195.80304961 204.07004895 207.50511222 215.16999857 202.32541172]
 [211.21108933 195.70373987 199.59085767 202.49908426 198.86033505]
 [190.74774294 199.35237412 200.5376301  196.88699046 197.13461013]
 [188.35900856 212.59983281 193.84360984 210.65257211 192.94384448]
 [218.18879211 206.35179999 207.14994487 199.69879495 205.01750762]]


Problem 5: Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

In [29]:
arr1=np.random.randint(1,17,(4,4))
print("Oringinal:",arr1)
arr1[:,[0,1,2,3]]=arr1[:,[3,2,1,0]]
print("Swaped:",arr1)

Oringinal: [[ 2 12 12 16]
 [13  3  4 14]
 [ 7 16  5 10]
 [15  1 10 14]]
Swaped: [[16 12 12  2]
 [14  4  3 13]
 [10  5 16  7]
 [14 10  1 15]]


Problem 6: Write a NumPy program to swap rows and columns of a given array in reverse order.

In [36]:
arr=np.random.randint(1,20,(5,5))
print("Original:\n",arr)
a=arr[::-1,::-1]
print("\n\n",a)

Original:
 [[13  1 10 10  3]
 [16  2 15  6  6]
 [14  7  4 12 10]
 [ 9  8 11 16 11]
 [ 7  2 11  2  2]]


 [[ 2  2 11  2  7]
 [11 16 11  8  9]
 [10 12  4  7 14]
 [ 6  6 15  2 16]
 [ 3 10 10  1 13]]


Problem 7: Write a NumPy program to multiply two given arrays of the same size element-by-element.

In [40]:
arr1=np.random.randint(20,30,(5,5))
arr2=np.random.randint(40,50,(5,5))
arr=arr1*arr2
print(arr1,"\n*\n",arr2,"\n=\n",arr)

[[27 29 22 25 28]
 [22 26 25 29 20]
 [23 24 24 23 29]
 [22 27 28 20 29]
 [22 22 24 24 25]] 
*
 [[43 45 45 46 41]
 [41 42 44 41 48]
 [48 41 40 44 42]
 [40 44 43 42 45]
 [47 42 45 45 48]] 
=
 [[1161 1305  990 1150 1148]
 [ 902 1092 1100 1189  960]
 [1104  984  960 1012 1218]
 [ 880 1188 1204  840 1305]
 [1034  924 1080 1080 1200]]


Problem 8: Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [41]:
num=np.random.randint(2,10,(3,3))
print(num)

[[4 8 5]
 [5 8 7]
 [3 7 2]]


Problem 9: Write a NumPy program to create a 3x3x3 array with random values.
Expected Output:

[[[ 0.48941799 0.58722213 0.43453926]
[ 0.94497547 0.81081709 0.1510409 ]
[ 0.66657127 0.29494755 0.48047144]]
[[ 0.02287253 0.95232614 0.32264936]
[ 0.67009741 0.25458304 0.16290913]
[ 0.15520198 0.86826529 0.9679322 ]]
[[ 0.13503103 0.02042211 0.24683897]
[ 0.97852158 0.22374748 0.10798856]
[ 0.62032646 0.5893892 0.16958144]]]

In [45]:
np.random.rand(3,3,3)

array([[[0.27825359, 0.10121887, 0.95091834],
        [0.27879708, 0.10655431, 0.5255431 ],
        [0.39343869, 0.73908909, 0.79533094]],

       [[0.03928951, 0.30606012, 0.31469228],
        [0.97800315, 0.74971691, 0.71382059],
        [0.79736848, 0.58486546, 0.75979457]],

       [[0.50960927, 0.02239602, 0.47495689],
        [0.66597053, 0.99024468, 0.43816899],
        [0.90308117, 0.94919529, 0.54581488]]])

Problem 10: Write a Python program to find the maximum and minimum value of a given flattened array.

In [50]:
arr=np.random.randint(1,10,(5,5))
print(arr)
print(np.max(arr))
print(np.min(arr))

[[5 8 1 4 2]
 [4 1 7 2 7]
 [8 3 9 1 9]
 [1 3 3 8 1]
 [8 5 4 2 3]]
9
1


Problem 11: Write a NumPy program to add, subtract, multiply, divide arguments element-wise.     
Expected Output:
Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25

In [55]:
n1=np.array([1])
n2=np.array([4])
print("Add:",float(n1+n2))
print("Subtract:",float(n1-n2))
print("Multiply:",float(n1*n2))
print("Divide:",float(n1/n2))

Add: 5.0
Subtract: -3.0
Multiply: 4.0
Divide: 0.25


Problem 12: Write a NumPy program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array
Expected Output:
Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

In [56]:
arr=np.array([0,1,2,3,4,5,6])
print(pow(arr,3))

[  0   1   8  27  64 125 216]


Problem 13: Create a Python project to guess a number that has randomly selected.

In [58]:
a=np.random.randint(1,16)
num=int(input("Enter number between 1 to 15:\n"))
if num==a:
    print("You guess the correct number")
else:
    print("Sorry,The random number is",a)

Enter number between 1 to 15:
12
Sorry,The random number is 10


Problem 14: Write a NumPy program to create a 2D array with 1 on the border and 0 inside.        
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

In [64]:
arr = np.ones((5, 5))
print("Original array:\n",arr,"\n")
arr[1:-1, 1:-1] = 0
print("1 on the border and 0 inside in the array\n",arr)


Original array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

1 on the border and 0 inside in the array
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Problem 15: Write a NumPy program to append values to the end of an array.                      
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [66]:
arr = np.array([10, 20, 30])
print("Original array:", arr)
arr = np.append(arr, [40, 50, 60, 70, 80, 90])
print("After append values to the end of the array:", arr)

Original array: [10 20 30]
After append values to the end of the array: [10 20 30 40 50 60 70 80 90]
